"""PDF report generation helpers."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any

from fpdf import FPDF

from src.config import get_config


def _to_pdf_text(value: Any) -> str:
    """Convert text to a latin-1-safe representation for core PDF fonts.

    Args:
        value: Value to normalize for PDF rendering.

    Returns:
        A text string that can be rendered by Helvetica without unicode errors.
    """
    text = str(value)
    text = text.replace("—", "-").replace("–", "-").replace("’", "'").replace("“", '"').replace("”", '"')
    return text.encode("latin-1", "replace").decode("latin-1")


def _soft_wrap_value(value: Any, chunk_size: int = 32) -> str:
    """Insert spaces in long tokens so PDF text wrapping never fails.

    Args:
        value: Any value to render in the PDF.
        chunk_size: Maximum continuous token length before inserting spaces.

    Returns:
        A string safe for ``multi_cell`` rendering.
    """
    text = _to_pdf_text(value)
    if len(text) <= chunk_size:
        return text
    return " ".join(text[index : index + chunk_size] for index in range(0, len(text), chunk_size))


def _write_record_field(pdf: FPDF, label: str, value: Any) -> None:
    """Write one provenance field using a safe full-width multi-cell.

    Args:
        pdf: Active PDF document instance.
        label: Field label.
        value: Field value.
    """
    pdf.set_x(pdf.l_margin)
    safe_text = f"{label}: {_soft_wrap_value(value)}"
    pdf.multi_cell(pdf.epw, 8, safe_text)


def generate_report(result: dict[str, Any], record: dict[str, Any], output_path: str) -> str:
    """Generate a PDF analysis report and save it to disk.

    Args:
        result: Analysis result dictionary with verdict and score details.
        record: Provenance record dictionary with owner/CID/tx/timestamp.
        output_path: Destination file path for the generated PDF.

    Returns:
        The output path where the report was saved.
    """
    config = get_config()
    threshold = float(config.get("analysis", {}).get("threshold", 0.75))

    pdf = FPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Title
    pdf.set_font("Helvetica", "B", 20)
    pdf.cell(0, 12, _to_pdf_text("VideoGuard Analysis Report"), ln=True)
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 11)
    pdf.cell(0, 8, _to_pdf_text(f"Analysis Date/Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"), ln=True)
    pdf.ln(6)

    # Section 1 - Verdict
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _to_pdf_text("Section 1 - Verdict"), ln=True)
    verdict = _to_pdf_text(result.get("verdict", "UNKNOWN"))
    pdf.set_font("Helvetica", "B", 24)
    pdf.cell(0, 14, verdict, ln=True)
    pdf.ln(4)

    # Section 2 - Score Breakdown table
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _to_pdf_text("Section 2 - Score Breakdown"), ln=True)
    headers = ["Audio Score", "Video Score", "Final Score", "Threshold"]
    values = [
        f"{float(result.get('audio_score', 0.0)):.4f}",
        f"{float(result.get('video_score', 0.0)):.4f}",
        f"{float(result.get('final_score', 0.0)):.4f}",
        f"{threshold:.4f}",
    ]

    col_width = 45
    row_height = 10
    pdf.set_font("Helvetica", "B", 11)
    for header in headers:
        pdf.cell(col_width, row_height, _to_pdf_text(header), border=1, align="C")
    pdf.ln(row_height)
    pdf.set_font("Helvetica", "", 11)
    for value in values:
        pdf.cell(col_width, row_height, _to_pdf_text(value), border=1, align="C")
    pdf.ln(row_height + 4)

    # Section 3 - Provenance Record
    pdf.set_font("Helvetica", "B", 14)
    pdf.cell(0, 10, _to_pdf_text("Section 3 - Provenance Record"), ln=True)
    pdf.set_font("Helvetica", "", 11)
    _write_record_field(pdf, "Owner", record.get("owner", "N/A"))
    _write_record_field(pdf, "CID", record.get("cid", "N/A"))
    _write_record_field(pdf, "TX Hash", record.get("tx_hash", "N/A"))
    _write_record_field(pdf, "Timestamp", record.get("timestamp", "N/A"))

    # Footer
    pdf.set_y(-20)
    pdf.set_font("Helvetica", "I", 9)
    pdf.cell(0, 10, _to_pdf_text("Generated by VideoGuard - Academic project. Not legal proof."), align="C")

    destination = Path(output_path)
    destination.parent.mkdir(parents=True, exist_ok=True)
    pdf.output(str(destination))
    return str(destination)

